# This is a basic workflow to help you get started with Actions

name: Deploy to Firebase Functions on PR
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-backend-each-branch:
    timeout-minutes: 15
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: './functions/package-lock.json'
      - name: Install Functions Dependencies
        run: npm install && npm install -g firebase-tools
        working-directory: functions
      - name: npm ci
        run: npm ci
        working-directory: functions
      - name: npm run lint
        run: npm run lint
        working-directory: functions
      - name: npm run build
        run: npm run build
        working-directory: functions
      # - name: Set this PR environment with branch name
      #   run: npm run set:branch -- --token=${{ secrets.FIREBASE_SECRET }}
      #   env:
      #     FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
      #   working-directory: functions
      - name: Set firebase env
        run: firebase use development --token $FIREBASE_SECRET
        working-directory: functions
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
      - name: Set firebase env
        run: firebase functions:config:set branch.name=$(git rev-parse --abbrev-ref HEAD) --token $FIREBASE_SECRET
        working-directory: functions
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
      - name: deploy functions to PR enviroment
        run:  BRANCH=`git rev-parse --abbrev-ref HEAD` && firebase deploy --only functions:sdkV4-${BRANCH} --token=${{ secrets.FIREBASE_SECRET }} 
        working-directory: functions
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        